# Pandas Tutorial: Complete Guide

This notebook follows a step-by-step learning flow for Pandas.

## Topics in Order
1. Series & DataFrame - basic data structures
2. Data Loading - CSV, JSON, Excel read/write
3. Data Exploration - `head()`, `info()`, `describe()`
4. Indexing & Selection - `loc`, `iloc`
5. Data Cleaning - null values, duplicates
6. Groupby & Aggregation
7. Merging & Joining DataFrames

Pandas is a fast, powerful, and easy-to-use open-source data analysis and manipulation library built on top of Python. It is widely used in Machine Learning and Data Science workflows.

**Why use Pandas?**
- Efficient data manipulation and analysis.
- Handles structured data easily (CSV, JSON, Excel, SQL, etc.).
- Essential for data preprocessing in ML workflows.

**Importance in ML:**
- Data cleaning: handle missing values and duplicates.
- Feature engineering: create new features from existing data.
- Data exploration: summarize and visualize datasets quickly.

## 1. Series & DataFrame

Pandas ke do basic data structures yeh hain:
- `Series`: one-dimensional labeled data
- `DataFrame`: two-dimensional table with rows and columns

Is section mein hum dekhain ge ke series aur dataframe kaise create hote hain aur kaise print kiye jate hain.

In [1]:
import pandas as pd
print('Pandas Version:', pd.__version__)

Pandas Version: 2.2.3

In [2]:
# Creating Series
series_from_list = pd.Series([10, 20, 30, 40, 50], name='numbers')
series_from_dict = pd.Series({'a':100,'b':200,'c':300}, name='DictSeries')
print(series_from_list)
print(series_from_dict)

0    10
1    20
2    30
3    40
4    50
Name: numbers, dtype: int64
a    100
b    200
c    300
Name: DictSeries, dtype: int64

In [3]:
# Creating DataFrames
data = {
    'Name': ['Alice','Bob','Charlie','David'],
    'Age': [25,30,35,40],
    'City': ['New York','Los Angeles','Chicago','Houston']
}
df = pd.DataFrame(data)
print(df)

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    David   40      Houston

## 2. Data Loading

Pandas multiple file formats ko support karta hai:
- `read_csv()` for CSV files
- `read_json()` for JSON files
- `read_excel()` / `to_excel()` for Excel workbooks

Neeche sample `data/` folder ke actual files use kiye gaye hain.

In [6]:
#load json file
json_data = pd.read_json('./data/dummy_students.json')
print(json_data)

   StudentID    Name  Age Grade       City
0        101     Ali   20     A     Lahore
1        102    Sara   21     B    Karachi
2        103   Ahmed   19     A  Islamabad
3        104    Zara   22     C     Multan
4        105  Hassan   20     B   Peshawar

In [7]:
# Read CSV from the sample data folder
df_csv = pd.read_csv('./data/dummy_students.csv')

In [9]:
df_csv.head(5)

   StudentID    Name  Age Grade       City
0      101.0     Ali   20     A     Lahore
1        NaN    Sara   21     B    Karachi
2      103.0   Ahmed   19     A  Islamabad
3      104.0    Zara   22     C     Multan
4      105.0  Hassan   20     B   Peshawar

In [ ]:
# Read JSON from the sample data folder
json_path = './data/dummy_students.json'
df_json = pd.read_json(json_path)

In [10]:
import pandas as pd

# Read the Excel file (adjust path if needed)
df_customer = pd.read_excel('./data/customer_data.xlsx')

In [11]:
df_customer.head()

  Customer  Amount
0      Ali     100
1     Sara     200
2      Ali     150
3    Ahmed     300
4     Sara     250

In [14]:
df_customer.tail(1)

   Customer  Amount
19    Ahmed     300

In [18]:


# Find top customer
top_customer = df_customer.groupby('Customer')['Amount'].sum().idxmin()
top_amount = df_customer.groupby('Customer')['Amount'].sum().min()

print("Top customer:", top_customer)
print("Total amount bought:", top_amount)

Top customer: Ali
Total amount bought: 770

In [ ]:
# Excel read/write example
excel_path = './data/dummy_students.csv'
df_csv.to_excel(excel_path, index=False)
df_excel = pd.read_excel(excel_path)
print(df_excel.head())

## 3. Data Exploration

Data load hone ke baad in methods se dataset ko quickly inspect kiya jata hai:
- `head()` aur `tail()` for sample rows
- `info()` for columns, data types, aur missing values
- `describe()` for summary statistics

Ye checks data quality aur structure samajhne ke liye useful hote hain.

In [19]:
print(pd.options.display.min_rows)
print(pd.options.display.max_rows)

#In my system the number is 60, which means that if the DataFrame contains more than 60 rows, the print(df) statement will return only the headers and the first and last 5 rows.

10
60

In [20]:
df_csv.head()

   StudentID    Name  Age Grade       City
0      101.0     Ali   20     A     Lahore
1        NaN    Sara   21     B    Karachi
2      103.0   Ahmed   19     A  Islamabad
3      104.0    Zara   22     C     Multan
4      105.0  Hassan   20     B   Peshawar

In [21]:
# Data Exploration
df_csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   StudentID  4 non-null      float64
 1   Name       5 non-null      object
 2   Age        5 non-null      int64
 3   Grade      5 non-null      object
 4   City       5 non-null      object
dtypes: float64(1), int64(1), object(3)
memory usage: 332.0+ bytes

### Understanding `df.info()` in Pandas

The `df.info()` method in Pandas provides a concise summary of a DataFrame, which helps us quickly understand the structure and content of the dataset.


**What `df.info()` tells us:**

1. **Type of object**: `<class 'pandas.core.frame.DataFrame'>` shows that this is a Pandas DataFrame.
2. **Index range**: `RangeIndex: 5 entries, 0 to 4` indicates 5 rows with indices from 0 to 4.
3. **Columns info**:

   * Column names (`StudentID`, `Name`, `Age`, `Grade`, `City`)
   * Number of non-null entries in each column (`5 non-null` means no missing values)
   * Data type of each column (`int64` for numbers, `object` for text)
4. **Data types summary**: `dtypes: int64(2), object(3)` shows there are 2 numeric columns and 3 object (text) columns.
5. **Memory usage**: `memory usage: 332.0+ bytes` shows the memory consumed by the DataFrame.

**Why we use it:**

* Quickly check the structure of the dataset.
* Identify missing values.
* Understand data types for analysis or preprocessing.
* Optimize memory usage if working with large datasets.

---

This method is essential for **initial data exploration** to understand what kind of data we are working with before analysis.

In [22]:
df_csv.describe()

        StudentID        Age
count    4.000000   5.000000
mean   103.250000  20.400000
std      1.707825   1.140175
min    101.000000  19.000000
25%    102.500000  20.000000
50%    103.500000  20.000000
75%    104.250000  21.000000
max    105.000000  22.000000

# Understanding df.describe()

`df.describe()` gives a quick summary of your dataset, showing count, mean, standard deviation, min, max, and quartiles.

It helps you understand the basic stats of your data in just a glance, like average age, range, and distribution.

In [23]:
print(df.head(3))

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

In [24]:
print(df.tail(2))

      Name  Age     City
2  Charlie   35  Chicago
3    David   40  Houston

## 4. Indexing & Selection

Pandas mein rows aur columns ko select karne ke liye different methods use hote hain:
- `df['col']` for a single column
- `df[['col1', 'col2']]` for multiple columns
- `iloc` for position-based selection
- `loc` for label-based selection
- boolean filtering for specific conditions

In [ ]:
df.head()

In [25]:
# Indexing & Filtering
print(df_csv['Name'])

0       Ali
1      Sara
2     Ahmed
3      Zara
4    Hassan
Name: Name, dtype: object

In [26]:
print(df_csv[['Name','Age']])

     Name  Age
0     Ali   20
1    Sara   21
2   Ahmed   19
3    Zara   22
4  Hassan   20

In [27]:
df_csv.head()

   StudentID    Name  Age Grade       City
0      101.0     Ali   20     A     Lahore
1        NaN    Sara   21     B    Karachi
2      103.0   Ahmed   19     A  Islamabad
3      104.0    Zara   22     C     Multan
4      105.0  Hassan   20     B   Peshawar

In [29]:
print(df_csv.iloc[2])

StudentID        103.0
Name             Ahmed
Age                 19
Grade                A
City         Islamabad
Name: 2, dtype: object

In [32]:
df_indexed = df_csv.set_index('Name')

# print with index
print(df_indexed.loc['Zara'])

StudentID     104.0
Age              22
Grade             C
City         Multan
Name: Zara, dtype: object

In [33]:
print(df[df['Age'] > 30])

      Name  Age     City
2  Charlie   35  Chicago
3    David   40  Houston

In [35]:
df_csv.head()

   StudentID    Name  Age Grade       City
0      101.0     Ali   20     A     Lahore
1        NaN    Sara   21     B    Karachi
2      103.0   Ahmed   19     A  Islamabad
3      104.0    Zara   22     C     Multan
4      105.0  Hassan   20     B   Peshawar

In [37]:
# Value in first row, 'City' column
print(df_csv.loc[4, 'Age'])

20

In [39]:
# Rows where Name is 'Sara'
print(df_csv.loc[df_csv['Name'] == 'Sara'])

   StudentID  Name  Age Grade     City
1        NaN  Sara   21     B  Karachi

# sorting

In [40]:
# Sorting, Grouping & Merging
print(df.sort_values(by='Age'))

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    David   40      Houston

In [42]:
print(df_csv.sort_values(by='Name', ascending=False))

   StudentID    Name  Age Grade       City
3      104.0    Zara   22     C     Multan
1        NaN    Sara   21     B    Karachi
4      105.0  Hassan   20     B   Peshawar
0      101.0     Ali   20     A     Lahore
2      103.0   Ahmed   19     A  Islamabad

In [43]:
import pandas as pd

s = pd.Series([30, 10, 40, 20])
print("Original Series:\n", s)

# Sort ascending
s_sorted = s.sort_values()
print("\nSorted Series (Ascending):\n", s_sorted)

# Sort descending
s_sorted_desc = s.sort_values(ascending=False)
print("\nSorted Series (Descending):\n", s_sorted_desc)

Original Series:
 0    30
1    10
2    40
3    20
dtype: int64

Sorted Series (Ascending):
 1    10
3    20
0    30
2    40
dtype: int64

Sorted Series (Descending):
 2    40
0    30
3    20
1    10
dtype: int64

In [ ]:
data = {'Name': ['Ali', 'Sara', 'Ahmed'], 'Age':[20, 22, 19], 'Score':[85, 90, 80]}
df = pd.DataFrame(data)
print("Original DataFrame:\n", df)

# Sort by single column
df_sorted_age = df.sort_values(by='Age')
print("\nSorted by Age:\n", df_sorted_age)

# Sort by multiple columns
df_sorted_age_score = df.sort_values(by=['Age', 'Score'], ascending=[False, True])
print("\nSorted by Age ascending, Score descending:\n", df_sorted_age_score)

Original DataFrame:
     Name  Age  Score
0    Ali   20     85
1   Sara   22     90
2  Ahmed   19     80

Sorted by Age:
     Name  Age  Score
2  Ahmed   19     80
0    Ali   20     85
1   Sara   22     90

Sorted by Age ascending, Score descending:
     Name  Age  Score
2  Ahmed   19     80
0    Ali   20     85
1   Sara   22     90

## 6. Groupby & Aggregation

`groupby()` data ko groups mein split karta hai aur phir har group par summary calculation karta hai.
Aksar use hone wale aggregations:
- mean
- sum
- count
- min / max

In [49]:
df_group = pd.DataFrame({
    'Department': ['HR', 'IT', 'HR', 'IT'],
    'Salary': [50000, 60000, 55000, 65000],
    'Employee': ['A', 'B', 'C', 'D']
})
df_group.head()

  Department  Salary Employee
0         HR   50000        A
1         IT   60000        B
2         HR   55000        C
3         IT   65000        D

In [50]:
print(df_group.groupby('Department')['Salary'].mean())
print(df_group.groupby('Department').agg(average_salary=('Salary', 'mean'), employee_count=('Employee', 'count')))

Department
HR    52500.0
IT    62500.0
Name: Salary, dtype: float64
            average_salary  employee_count
Department
HR                 52500.0               2
IT                 62500.0               2

## 7. Merging & Joining DataFrames

Multiple DataFrames ko combine karne ke liye `merge()` use hota hai.
Common join types:
- `inner`
- `left`
- `right`
- `outer`

Join type choose karne se output rows ka behavior control hota hai.

In [51]:
df1 = pd.DataFrame({'ID': [1, 2, 3], 'Name': ['A', 'B', 'C']})
df2 = pd.DataFrame({'ID': [2, 3, 4], 'Score': [90, 95, 85]})

In [52]:
df1.head()

   ID Name
0   1    A
1   2    B
2   3    C

In [53]:
df2.head()

   ID  Score
0   2     90
1   3     95
2   4     85

In [ ]:
merged_inner = pd.merge(df1, df2, on='ID', how='inner')
merged_left = pd.merge(df1, df2, on='ID', how='left')

print('Inner join:')
print(merged_inner)

Inner join:
   ID Name  Score
0   2    B     90
1   3    C     95

In [56]:
print('\nLeft join:')
print(merged_left)

Left join:
   ID Name  Score
0   1    A    NaN
1   2    B   90.0
2   3    C   95.0

In [ ]:
# Saving Data
df.to_csv('output.csv', index=False)
df.to_json('output.json', orient='records')



**Assignment:**

1. Create a Pandas Series with values `[50, 20, 40, 10, 30]` and sort it in ascending order.
2. Create a DataFrame with columns `Name = ['Ali','Sara','Ahmed','Zara']` and `Score = [85, 95, 80, 90]`. Sort the DataFrame by `Score` descending.
3. Print both sorted outputs.

**Expected Output:**

```python
# Series ascending: 10, 20, 30, 40, 50

# DataFrame sorted by Score descending:
#    Name  Score
# 1  Sara     95
# 3  Zara     90
# 0   Ali     85
# 2  Ahmed    80
```

In [ ]:
# Series sorting
s = pd.Series([50, 20, 40, 10, 30])
s_sorted = s.sort_values()
print("Sorted Series (Ascending):")
print(s_sorted)

# DataFrame sorting
df = pd.DataFrame({'Name': ['Ali','Sara','Ahmed','Zara'], 'Score': [85,95,80,90]})
df_sorted = df.sort_values(by='Score', ascending=False)
print("\nDataFrame sorted by Score (Descending):")
print(df_sorted)

Great! Here are **2 more mini exercises** for students, keeping them short and focused on Pandas basics like sorting and selection:

---

**Exercise 2:**

* Create a DataFrame:

```python
data = {'City':['London','Paris','Tokyo','Dubai'], 'Population':[9000000, 2140000, 13960000, 3330000]}
```

* Sort the DataFrame by `Population` in ascending order.
* Select and print only the `City` column of the sorted DataFrame.

**Expected Output:**

```python
# City
# 1    Paris
# 3     Dubai
# 0    London
# 2     Tokyo
```

---

**Exercise 3:**

* Create a Series with values `[5, 2, 9, 1, 7]`.
* Sort the Series descending and select the top 3 values only.
* Print the result.

**Expected Output:**

```python
# 2    9
# 4    7
# 0    5
```