# Pandas Data Cleaning Basic Notebook

**Goal:** Is notebook mein hum aik messy student dataset banayen gy, phir us par complete basic data cleaning perform karen gy.

**Level:** Beginner

**Topics Covered:**
1. Load dataset
2. Check shape, columns, info
3. Missing values check
4. Missing values handle
5. Duplicate rows remove
6. Column names clean
7. Text cleaning
8. Wrong values replace
9. Data type conversion
10. Invalid rows remove
11. Cleaned dataset save

## 1. Import Pandas

Pandas data ko read, clean, filter aur analyze karne ke liye use hota hai.

In [111]:
import pandas as pd

## 2. Create a Messy Dataset

Yahan hum practice ke liye aik messy student dataset create kar rahe hain. Real-life data bhi aksar isi tarah messy hota hai.

In [112]:
data = {
    " Student Name ": [" Ali ", "Sara", "Ahmed", "Ali ", "Bilal", "Hina", None, "Usman", "Maham", "Ahmed", "Zara", "Hamza", "Ayesha", "sara", "Danish"],
    "Age": [20, 22, None, 20, -5, 21, 23, 24, None, 19, 22, 200, 18, 22, 25],
    "City ": ["lahore", "Lahore", "LHR", "lahore", "karachi", None, "Islamabad", "islamabad ", "KHI", "LHR", "Karachi", "lahore", "islamabad", "Lahore", "Multan"],
    "Gender": ["M", "F", "M", "M", "M", "F", "F", "Male", "Female", "M", "F", "M", "F", "F", None],
    "Marks": [85, 90, None, 85, 70, 88, 92, -10, 78, 81, None, 95, 76, 90, 89],
    "Admission Date": ["2024-01-10", "2024/01/12", "10-01-2024", "2024-01-10", None, "2024-02-01", "2024-02-05", "2024-02-08", "2024-03-01", "2024-03-05", "2024-03-10", "invalid-date", "2024-04-01", "2024-01-12", "2024-04-15"],
    "Unnamed: 0": list(range(1, 16))
}

messy_df = pd.DataFrame(data)
messy_df

    Student Name     Age       City   Gender  Marks Admission Date  Unnamed: 0
0            Ali    20.0      lahore       M   85.0     2024-01-10           1
1            Sara   22.0      Lahore       F   90.0     2024/01/12           2
2           Ahmed    NaN         LHR       M    NaN     10-01-2024           3
3            Ali    20.0      lahore       M   85.0     2024-01-10           4
4           Bilal   -5.0     karachi       M   70.0           None           5
5            Hina   21.0        None       F   88.0     2024-02-01           6
6            None   23.0   Islamabad       F   92.0     2024-02-05           7
7           Usman   24.0  islamabad     Male  -10.0     2024-02-08           8
8           Maham    NaN         KHI  Female   78.0     2024-03-01           9
9           Ahmed   19.0         LHR       M   81.0     2024-03-05          10
10           Zara   22.0     Karachi       F    NaN     2024-03-10          11
11          Hamza  200.0      lahore       M   95.0   invalid-date          12
12         Ayesha   18.0   islamabad       F   76.0     2024-04-01          13
13           sara   22.0      Lahore       F   90.0     2024-01-12          14
14         Danish   25.0      Multan    None   89.0     2024-04-15          15

## 3. Save and Load Dataset

Real case mein hum CSV file read karte hain. Is liye pehle dataset ko CSV mein save karen gy, phir read karen gy.

In [113]:
# messy_df.to_csv("messy_student_dataset.csv", index=False)

df = pd.read_csv("./data/messy_student_dataset.csv")
df.head()

   Student Name    Age    City  Gender  Marks Admission Date  Unnamed: 0
0           Ali   20.0   lahore      M   85.0     2024-01-10           1
1           Sara  22.0   Lahore      F   90.0     2024/01/12           2
2          Ahmed   NaN      LHR      M    NaN     10-01-2024           3
3           Ali   20.0   lahore      M   85.0     2024-01-10           4
4          Bilal  -5.0  karachi      M   70.0            NaN           5

## 4. Check Dataset Shape

`shape` se rows aur columns ka count pata chalta hai.

In [114]:
df.shape

(15, 7)

## 5. Check Column Names

Column names mein extra spaces ya unwanted columns ho sakte hain.

In [115]:
df.columns

Index([' Student Name ', 'Age', 'City ', 'Gender', 'Marks', 'Admission Date',
       'Unnamed: 0'],
      dtype='object')

## 6. Check Basic Information

`info()` se non-null values aur data types pata chalte hain.

In [116]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0    Student Name   14 non-null     object
 1   Age             13 non-null     float64
 2   City            14 non-null     object
 3   Gender          14 non-null     object
 4   Marks           13 non-null     float64
 5   Admission Date  14 non-null     object
 6   Unnamed: 0      15 non-null     int64
dtypes: float64(2), int64(1), object(4)
memory usage: 972.0+ bytes

## 7. Summary Statistics

`describe()` numeric columns ka basic summary deta hai.

In [117]:
df.describe()

              Age      Marks  Unnamed: 0
count   13.000000  13.000000   15.000000
mean    33.153846  77.615385    8.000000
std     50.698202  27.250500    4.472136
min     -5.000000 -10.000000    1.000000
25%     20.000000  78.000000    4.500000
50%     22.000000  85.000000    8.000000
75%     23.000000  90.000000   11.500000
max    200.000000  95.000000   15.000000

## 8. Check Missing Values

Missing values ka count har column ke liye check karte hain.

In [118]:
df.isnull().sum().sort_values(ascending=True)

Unnamed: 0        0
 Student Name     1
City              1
Gender            1
Admission Date    1
Age               2
Marks             2
dtype: int64

## 9. Check Duplicate Rows

Duplicate rows analysis ko wrong kar sakti hain.

In [119]:
df.duplicated().sum()

0

## 10. Clean Column Names

Column names ko simple aur readable banate hain:
- extra spaces remove
- lowercase
- spaces ko underscore mein convert

In [120]:
df.columns = df.columns.str.strip()
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(" ", "_")

df.columns

Index(['student_name', 'age', 'city', 'gender', 'marks', 'admission_date',
       'unnamed:_0'],
      dtype='object')

## 11. Drop Unnecessary Column

`unnamed:_0` jaisi columns aksar index ki wajah se ban jati hain. Isko remove kar dete hain.

In [121]:
df = df.drop(columns=["Unnamed: 0"])
df.head()

KeyError: "['Unnamed: 0'] not found in axis"

## 12. Remove Extra Spaces from Text Columns

Text data mein extra spaces hidden hoti hain. Example: ` Ali ` ko `Ali` banana.

In [ ]:
df['student_name'] = df['student_name'].str.strip()
df['city'] = df['city'].str.strip()

df.head()

  student_name   age     city gender  marks admission_date
0          Ali  20.0   lahore      M   85.0     2024-01-10
1         Sara  22.0   Lahore      F   90.0     2024/01/12
2        Ahmed   NaN      LHR      M    NaN     10-01-2024
3          Ali  20.0   lahore      M   85.0     2024-01-10
4        Bilal  -5.0  karachi      M   70.0            NaN

## 13. Standardize Text Case

City names aur student names ko proper format mein convert karte hain.

In [ ]:
df.head()

  student_name   age     city gender  marks admission_date
0          Ali  20.0   lahore      M   85.0     2024-01-10
1         Sara  22.0   Lahore      F   90.0     2024/01/12
2        Ahmed   NaN      LHR      M    NaN     10-01-2024
3          Ali  20.0   lahore      M   85.0     2024-01-10
4        Bilal  -5.0  karachi      M   70.0            NaN

In [ ]:
df['student_name'] = df['student_name'].str.title()
df['city'] = df['city'].str.title()

df[['student_name', 'city']].head(10)

  student_name       city
0          Ali     Lahore
1         Sara     Lahore
2        Ahmed        Lhr
3          Ali     Lahore
4        Bilal    Karachi
5         Hina        NaN
6          NaN  Islamabad
7        Usman  Islamabad
8        Maham        Khi
9        Ahmed        Lhr

## 14. Check Unique Values

Unique values se spelling mistakes aur inconsistent values easily detect hoti hain.

In [ ]:
print("Cities:", df['city'].unique())
print("Gender:", df['gender'].unique())

Cities: ['Lahore' 'Lhr' 'Karachi' nan 'Islamabad' 'Khi' 'Multan']
Gender: ['M' 'F' 'Male' 'Female' nan]

## 15. Replace Wrong/Inconsistent Values

Examples:
- `Lhr` ko `Lahore`
- `Khi` ko `Karachi`
- `M` ko `Male`
- `F` ko `Female`

In [ ]:
df['city'] = df['city'].replace({
    "Lhr": "Lahore",
    "Khi": "Okara"
})

df['gender'] = df['gender'].replace({
    "M": "Male",
    "F": "Female"
})

print("Cities:", df['city'].unique())
print("Gender:", df['gender'].unique())

Cities: ['Lahore' 'Karachi' nan 'Islamabad' 'Okara' 'Multan']
Gender: ['Male' 'Female' nan]

## 16. Handle Missing Values

Basic method:
- Numeric columns mein missing values ko mean/median se fill kar sakte hain
- Text columns mein missing values ko `Unknown` se fill kar sakte hain

In [ ]:
df.head()

  student_name   age     city  gender  marks admission_date
0          Ali  20.0   Lahore    Male   85.0     2024-01-10
1         Sara  22.0   Lahore  Female   90.0     2024/01/12
2        Ahmed   NaN   Lahore    Male    NaN     10-01-2024
3          Ali  20.0   Lahore    Male   85.0     2024-01-10
4        Bilal  -5.0  Karachi    Male   70.0            NaN

In [ ]:
df['age'] = df['age'].fillna(df['age'].median())
df['marks'] = df['marks'].fillna(df['marks'].mean())
df['student_name'] = df['student_name'].fillna("Unknown")
df['city'] = df['city'].fillna("Unknown")
df['gender'] = df['gender'].fillna("Unknown")

df.isnull().sum()

C:\Users\PMLS\AppData\Local\Temp\ipykernel_17000\128941225.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['age'] = df['age'].fillna(df['age'].median())
C:\Users\PMLS\AppData\Local\Temp\ipykernel_17000\128941225.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['marks'] = df['marks'].fillna(df['marks'].mean())
C:\Users\PMLS\AppData\Local\Temp\ipykernel_17000\128941225.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['student_name'] = df['student_name'].fillna("Unknown")
C:\Users\PMLS\AppData\Local\Temp\ipykernel_17000\128941225.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['city'] = df['city'].fillna("Unknown")
C:\Users\PMLS\AppData\Local\Temp\ipykernel_17000\128941225.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['gender'] = df['gender'].fillna("Unknown")

student_name      0
age               0
city              0
gender            0
marks             0
admission_date    0
dtype: int64

## 17. Convert Date Column

Date column ko proper datetime format mein convert karte hain. Invalid dates ko `NaT` banaya jata hai using `errors='coerce'`.

In [ ]:
df["admission_date"].head()

0   2024-01-10
1   2024-02-01
2   2024-02-01
3   2024-01-10
4   2024-02-01
Name: admission_date, dtype: datetime64[ns]

In [ ]:
df['admission_date'] = pd.to_datetime(df['admission_date'], errors='coerce')

df[['admission_date']].head(15)

   admission_date
0      2024-01-10
1             NaT
2             NaT
3      2024-01-10
4             NaT
5      2024-02-01
6      2024-02-05
7      2024-02-08
8      2024-03-01
9      2024-03-05
10     2024-03-10
11            NaT
12     2024-04-01
13     2024-01-12
14     2024-04-15

In [ ]:
df['admission_date'] = df['admission_date'].fillna(pd.Timestamp('2024-02-01'))

In [ ]:
df.isnull().sum()

student_name      0
age               0
city              0
gender            0
marks             0
admission_date    0
dtype: int64

## 18. Fill Missing Dates

Basic class ke liye missing date ko mode se fill kar dete hain.

In [ ]:
most_common_date = df['admission_date'].mode()[0]

print("Most common admission date:", most_common_date)



df['admission_date'] = df['admission_date'].fillna(most_common_date)

df.isnull().sum()

Most common admission date: 2024-01-10 00:00:00

student_name      0
age               0
city              0
gender            0
marks             0
admission_date    0
dtype: int64

## 19. Remove Duplicate Rows

Ab duplicate rows remove karte hain.

In [ ]:
before = df.shape[0]
df = df.drop_duplicates()
after = df.shape[0]

print("Rows before removing duplicates:", before)
print("Rows after removing duplicates:", after)

Rows before removing duplicates: 15
Rows after removing duplicates: 14

## 20. Find Invalid Values

Age 0 se kam ya 100 se zyada ho to invalid maan sakte hain. Marks 0 se kam ya 100 se zyada ho to invalid hain.

In [ ]:
invalid_age = df[(df['age'] < 0) | (df['age'] > 100)]
invalid_marks = df[(df['marks'] < 0) | (df['marks'] > 100)]

print("Invalid Age Rows:")
display(invalid_age)

print("Invalid Marks Rows:")
display(invalid_marks)

Invalid Age Rows:

   student_name    age     city gender  marks admission_date
4         Bilal   -5.0  Karachi   Male   70.0     2024-02-01
11        Hamza  200.0   Lahore   Male   95.0     2024-02-01

Invalid Marks Rows:

  student_name   age       city gender  marks admission_date
7        Usman  24.0  Islamabad   Male  -10.0     2024-02-08

In [ ]:
df[(df['age'] >= 18) & (df['marks'] >= 50)]

   student_name    age       city gender  marks admission_date  unnamed:_0
0           Ali   20.0     Lahore      M   85.0     2024-01-10           1
1          Sara   22.0     Lahore      F   90.0     2024-01-10           2
3           Ali   20.0     Lahore      M   85.0     2024-01-10           4
5          Hina   21.0        NaN      F   88.0     2024-02-01           6
6           NaN   23.0  Islamabad      F   92.0     2024-02-05           7
9         Ahmed   19.0        Lhr      M   81.0     2024-03-05          10
11        Hamza  200.0     Lahore      M   95.0     2024-01-10          12
12       Ayesha   18.0  Islamabad      F   76.0     2024-04-01          13
13         Sara   22.0     Lahore      F   90.0     2024-01-12          14
14       Danish   25.0     Multan    NaN   89.0     2024-04-15          15

In [ ]:
df[~(df['city'] == 'Lahore')]

   student_name   age       city   gender      marks admission_date
4         Bilal  -5.0    Karachi     Male  70.000000     2024-02-01
5          Hina  21.0    Unknown   Female  88.000000     2024-02-01
6       Unknown  23.0  Islamabad   Female  92.000000     2024-02-05
7         Usman  24.0  Islamabad     Male -10.000000     2024-02-08
8         Maham  22.0      Okara   Female  78.000000     2024-03-01
10         Zara  22.0    Karachi   Female  77.615385     2024-03-10
12       Ayesha  18.0  Islamabad   Female  76.000000     2024-04-01
14       Danish  25.0     Multan  Unknown  89.000000     2024-04-15

## 21. Remove Invalid Rows

Invalid age aur marks wali rows remove karte hain.

In [ ]:
df = df[(df['age'] >= 0) & (df['age'] <= 100)]
df = df[(df['marks'] >= 0) & (df['marks'] <= 100)]

df

   student_name   age       city   gender      marks admission_date
0           Ali  20.0     Lahore     Male  85.000000     2024-01-10
1          Sara  22.0     Lahore   Female  90.000000     2024-01-10
2         Ahmed  22.0     Lahore     Male  77.615385     2024-01-10
5          Hina  21.0    Unknown   Female  88.000000     2024-02-01
6       Unknown  23.0  Islamabad   Female  92.000000     2024-02-05
8         Maham  22.0    Karachi   Female  78.000000     2024-03-01
9         Ahmed  19.0     Lahore     Male  81.000000     2024-03-05
10         Zara  22.0    Karachi   Female  77.615385     2024-03-10
12       Ayesha  18.0  Islamabad   Female  76.000000     2024-04-01
13         Sara  22.0     Lahore   Female  90.000000     2024-01-12
14       Danish  25.0     Multan  Unknown  89.000000     2024-04-15

## 22. Convert Data Types

Age ko integer mein convert karte hain. Marks ko 2 decimal tak round karte hain.

In [ ]:
df.head()

  student_name   age       city  gender      marks admission_date
0          Ali  20.0     Lahore    Male  85.000000     2024-01-10
1         Sara  22.0     Lahore  Female  90.000000     2024-01-10
2        Ahmed  22.0     Lahore    Male  77.615385     2024-01-10
5         Hina  21.0    Unknown  Female  88.000000     2024-02-01
6      Unknown  23.0  Islamabad  Female  92.000000     2024-02-05

In [ ]:
df['age'] = df['age'].astype(int)
df['marks'] = df['marks'].round(2)

df.dtypes

C:\Users\PMLS\AppData\Local\Temp\ipykernel_17000\2200578406.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['age'] = df['age'].astype(int)
C:\Users\PMLS\AppData\Local\Temp\ipykernel_17000\2200578406.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['marks'] = df['marks'].round(2)

student_name              object
age                        int32
city                      object
gender                    object
marks                    float64
admission_date    datetime64[ns]
dtype: object

## 23. Final Cleaned Dataset

Ab final cleaned dataset ready hai.

In [98]:
df.reset_index(drop=True, inplace=True)
df

   student_name  age       city   gender  marks admission_date
0           Ali   20     Lahore     Male   85.0     2024-01-10
1          Sara   22     Lahore   Female   90.0     2024-02-01
2         Ahmed   22     Lahore     Male   77.6     2024-02-01
3         Bilal   -5    Karachi     Male   70.0     2024-02-01
4          Hina   21    Unknown   Female   88.0     2024-02-01
5       Unknown   23  Islamabad   Female   92.0     2024-02-05
6         Usman   24  Islamabad     Male  -10.0     2024-02-08
7         Maham   22      Okara   Female   78.0     2024-03-01
8         Ahmed   19     Lahore     Male   81.0     2024-03-05
9          Zara   22    Karachi   Female   77.6     2024-03-10
10        Hamza  200     Lahore     Male   95.0     2024-02-01
11       Ayesha   18  Islamabad   Female   76.0     2024-04-01
12         Sara   22     Lahore   Female   90.0     2024-01-12
13       Danish   25     Multan  Unknown   89.0     2024-04-15

## 24. Save Cleaned Dataset

Cleaned dataset ko CSV file mein save kar lete hain.

In [122]:
df.to_csv("cleaned_student_dataset.csv", index=False)
print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!

## 25. Final Practice Task for Students

Students ko ye tasks do:

1. Dataset mein total students count karo.
2. Lahore city ke students filter karo.
3. Sab se zyada marks lene wala student find karo.
4. Gender wise average marks calculate karo.
5. Cleaned dataset ko Excel file mein save karo.

# Final Recap

Aaj hum ne basic data cleaning seekhi:

- Dataset load karna
- Shape, columns, info check karna
- Missing values handle karna
- Duplicate rows remove karna
- Column names clean karna
- Text values clean karna
- Wrong values replace karna
- Data types convert karna
- Invalid rows remove karna
- Cleaned dataset save karna

**Important Line:**

Agar data clean nahi hoga, to analysis aur machine learning ka result bhi accurate nahi hoga.