# Pandas Basic Preprocessing Notebook

## Topics Covered

1. Feature Scaling
2. Normalization vs Standardization
3. Encoding Categorical Data

**Dataset used:** Titanic-style beginner dataset created inside this notebook.

This notebook is designed for beginner students. Each topic includes a simple explanation and practical code.

## 1. Import Required Libraries

We need:

- `pandas` for creating and handling data
- `MinMaxScaler` for normalization
- `StandardScaler` for standardization
- `LabelEncoder` for label encoding

In [1]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler, StandardScaler, LabelEncoder

## 2. Create Dataset

We will use a small Titanic-style dataset.

This dataset contains:

- Numerical columns: `age`, `fare`
- Categorical columns: `sex`, `embarked`, `class`
- Target column: `survived`

This is useful because we can practice both scaling and encoding.

In [2]:
df = pd.read_csv("./data/Titanic-Dataset.csv")

In [3]:
df.head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

## 3. Basic Dataset Checking

Before applying scaling or encoding, always check the dataset first.

We will check:

- Dataset shape
- Column names
- Data types
- Missing values

In [4]:
print("Dataset Shape:", df.shape)
print("Column Names:")
print(df.columns)

print("Dataset Info:")
df.info()

Dataset Shape: (891, 12)
Column Names:
Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')
Dataset Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [5]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [6]:
print("Missing Values:")
print(df.isnull().sum().sort_values(ascending=False))

Missing Values:
Cabin          687
Age            177
Embarked         2
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
SibSp            0
Parch            0
Ticket           0
Fare             0
dtype: int64

## 4. Handle Missing Values

Scaling cannot be applied properly if numerical columns have missing values.

So we will fill:

- Missing `age` with mean age
- Missing `fare` with mean fare
- Missing `embarked` with mode, which means the most repeated value

In [7]:
df["Age"] = df["Age"].fillna(df["Age"].mean())
# df["Fare"] = df["Fare"].fillna(df["Fare"].mean())
df["Embarked"] = df["Embarked"].fillna(df["Embarked"].mode()[0])

print("Missing Values After Cleaning:")
print(df.isnull().sum())

display(df)

Missing Values After Cleaning:
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         0
dtype: int64

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.000000,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.000000,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.000000,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.000000,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.000000,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.699118,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.000000,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.000000,0,0,370376,7.7500,NaN,Q

In [9]:
#remove cabin column
df.drop("Cabin", axis=1, inplace=True)

In [10]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S

# Topic 1: Feature Scaling

## What is Feature Scaling?

Feature scaling means converting numerical columns into a similar scale.

Example:

- Age values may be between 18 and 60
- Fare values may be between 5 and 100

Machine learning models can give more importance to large numbers.

So we scale the data to make features balanced.

## Why is Feature Scaling Important?

Feature scaling is useful for many machine learning algorithms, especially:

- KNN
- SVM
- Logistic Regression
- Linear Regression
- Neural Networks

## Columns we will scale

We will scale:

- `age`
- `fare`

In [11]:
numerical_columns = ["Age", "Fare"]

display(df[numerical_columns])

           Age     Fare
0    22.000000   7.2500
1    38.000000  71.2833
2    26.000000   7.9250
3    35.000000  53.1000
4    35.000000   8.0500
..         ...      ...
886  27.000000  13.0000
887  19.000000  30.0000
888  29.699118  23.4500
889  26.000000  30.0000
890  32.000000   7.7500

[891 rows x 2 columns]

# Topic 2: Normalization vs Standardization

There are two common scaling methods:

1. Normalization
2. Standardization

## 2.1 Normalization

Normalization converts values into a fixed range, usually between **0 and 1**.

### Formula

```text
X_normalized = (X - min) / (max - min)
```

### Simple Explanation

If a value is minimum, it becomes 0.

If a value is maximum, it becomes 1.

Other values come between 0 and 1.

### When to Use Normalization

Use normalization when:

- You want all values between 0 and 1
- You are using KNN
- You are using neural networks
- Data does not follow normal distribution

In [18]:
minmax_scaler = MinMaxScaler()

df[["age_normalized", "fare_normalized"]] = minmax_scaler.fit_transform(df[["Age", "Fare"]])

print("Normalized Values:")
display(df[["Age", "age_normalized", "Fare", "fare_normalized"]])

Normalized Values:

           Age  age_normalized     Fare  fare_normalized
0    22.000000        0.271174   7.2500         0.014151
1    38.000000        0.472229  71.2833         0.139136
2    26.000000        0.321438   7.9250         0.015469
3    35.000000        0.434531  53.1000         0.103644
4    35.000000        0.434531   8.0500         0.015713
..         ...             ...      ...              ...
886  27.000000        0.334004  13.0000         0.025374
887  19.000000        0.233476  30.0000         0.058556
888  29.699118        0.367921  23.4500         0.045771
889  26.000000        0.321438  30.0000         0.058556
890  32.000000        0.396833   7.7500         0.015127

[891 rows x 4 columns]

## 2.2 Standardization

Standardization converts data around mean 0 and standard deviation 1.

### Formula

```text
X_standardized = (X - mean) / standard deviation
```

### Simple Explanation

After standardization:

- Mean becomes close to 0
- Standard deviation becomes close to 1

### When to Use Standardization

Use standardization when:

- You are using Logistic Regression
- You are using Linear Regression
- You are using SVM
- Data has outliers or different ranges

`11.18` **standard deviation** hai.

Humne data liya tha:

```text
Age = 20, 30, 40, 50
```

## Step 1: Mean nikaalo

```text
Mean = (20 + 30 + 40 + 50) / 4
Mean = 140 / 4
Mean = 35
```

## Step 2: Har value se mean minus karo

```text
20 - 35 = -15
30 - 35 = -5
40 - 35 = 5
50 - 35 = 15
```

## Step 3: In values ka square karo

```text
(-15)^2 = 225
(-5)^2  = 25
(5)^2   = 25
(15)^2  = 225
```

## Step 4: Squares ka average lo

```text
(225 + 25 + 25 + 225) / 4
= 500 / 4
= 125
```

## Step 5: Square root lo

```text
√125 = 11.18
```

So:

```text
Standard Deviation = 11.18
```

In [12]:
standard_scaler = StandardScaler()

df[["age_standardized", "fare_standardized"]] = standard_scaler.fit_transform(df[["Age", "Fare"]])

print("Standardized Values:")
display(df[["Age", "age_standardized", "Fare", "fare_standardized"]])

Standardized Values:

           Age  age_standardized     Fare  fare_standardized
0    22.000000         -0.592481   7.2500          -0.502445
1    38.000000          0.638789  71.2833           0.786845
2    26.000000         -0.284663   7.9250          -0.488854
3    35.000000          0.407926  53.1000           0.420730
4    35.000000          0.407926   8.0500          -0.486337
..         ...               ...      ...                ...
886  27.000000         -0.207709  13.0000          -0.386671
887  19.000000         -0.823344  30.0000          -0.044381
888  29.699118          0.000000  23.4500          -0.176263
889  26.000000         -0.284663  30.0000          -0.044381
890  32.000000          0.177063   7.7500          -0.492378

[891 rows x 4 columns]

## 2.3 Compare Normalization and Standardization

| Method | Output | Best Used For |
|---|---|---|
| Normalization | Values between 0 and 1 | KNN, Neural Networks |
| Standardization | Mean 0 and standard deviation 1 | SVM, Logistic Regression, Linear Regression |

### Important Point

Both methods are used for numerical data only.

We do not apply scaling directly on text columns.

In [13]:
comparison = df[[
    "Age", "age_normalized", "age_standardized",
    "Fare", "fare_normalized", "fare_standardized"
]]

display(comparison)

KeyError: "['age_normalized', 'fare_normalized'] not in index"

# Topic 3: Encoding Categorical Data

## What is Categorical Data?

Categorical data means text-based data or group-based data.

Examples:

- Male, Female
- Lahore, Karachi, Islamabad
- First, Second, Third

Machine learning models cannot understand text directly.

So we convert text values into numbers. This process is called **encoding**.

In [14]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,age_standardized,fare_standardized
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S,-0.592481,-0.502445
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,0.638789,0.786845
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S,-0.284663,-0.488854
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S,0.407926,0.420730
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S,0.407926,-0.486337

In [15]:
categorical_columns = ["Sex", "Embarked", "Pclass"]

display(df[categorical_columns])

        Sex Embarked  Pclass
0      male        S       3
1    female        C       1
2    female        S       3
3    female        S       1
4      male        S       3
..      ...      ...     ...
886    male        S       2
887  female        S       1
888  female        S       3
889    male        C       1
890    male        Q       3

[891 rows x 3 columns]

## 3.1 Label Encoding

Label Encoding converts categories into numbers.

Example:

```text
male = 1
female = 0
```

### When to Use Label Encoding

Use label encoding when:

- Column has only two categories
- Categories have order, like Low, Medium, High

Here we will apply Label Encoding on `sex`.

In [16]:
label_encoder = LabelEncoder()

df["sex_encoded"] = label_encoder.fit_transform(df["Sex"])

print("Label Encoding for Sex Column:")
display(df[["Sex", "sex_encoded"]])

Label Encoding for Sex Column:

        Sex  sex_encoded
0      male            1
1    female            0
2    female            0
3    female            0
4      male            1
..      ...          ...
886    male            1
887  female            0
888  female            0
889    male            1
890    male            1

[891 rows x 2 columns]

## 3.2 One-Hot Encoding

One-Hot Encoding creates separate columns for each category.

Example:

If the column is `class`:

```text
First
Second
Third
```

After one-hot encoding, it becomes:

```text
class_First  class_Second  class_Third
1            0             0
0            1             0
0            0             1
```

### When to Use One-Hot Encoding

Use one-hot encoding when categories have no natural order.

Examples:

- City
- Country
- Embarked port
- Class name

In [30]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [17]:
df_encoded = pd.get_dummies(df, columns=["Embarked", "Pclass"], drop_first=False)

print("Dataset After One-Hot Encoding:")
display(df_encoded)

Dataset After One-Hot Encoding:

,PassengerId,Survived,Name,Sex,Age,SibSp,Parch,Ticket,Fare,age_standardized,fare_standardized,sex_encoded,Embarked_C,Embarked_Q,Embarked_S,Pclass_1,Pclass_2,Pclass_3
0,1,0,"Braund, Mr. Owen Harris",male,22.000000,1,0,A/5 21171,7.2500,-0.592481,-0.502445,1,False,False,True,False,False,True
1,2,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000,1,0,PC 17599,71.2833,0.638789,0.786845,0,True,False,False,True,False,False
2,3,1,"Heikkinen, Miss. Laina",female,26.000000,0,0,STON/O2. 3101282,7.9250,-0.284663,-0.488854,0,False,False,True,False,False,True
3,4,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,1,0,113803,53.1000,0.407926,0.420730,0,False,False,True,True,False,False
4,5,0,"Allen, Mr. William Henry",male,35.000000,0,0,373450,8.0500,0.407926,-0.486337,1,False,False,True,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,"Montvila, Rev. Juozas",male,27.000000,0,0,211536,13.0000,-0.207709,-0.386671,1,False,False,True,False,True,False
887,888,1,"Graham, Miss. Margaret Edith",female,19.000000,0,0,112053,30.0000,-0.823344,-0.044381,0,False,False,True,True,False,False
888,889,0,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.699118,1,2,W./C. 6607,23.4500,0.000000,-0.176263,0,False,False,True,False,False,True
889,890,1,"Behr, Mr. Karl Howell",male,26.000000,0,0,111369,30.0000,-0.284663,-0.044381,1,True,False,False,True,False,False
890,891,0,"Dooley, Mr. Patrick",male,32.000000,0,0,370376,7.7500,0.177063,-0.492378,1,False,True,False,False,False,True

## Label Encoding vs One-Hot Encoding

**Label Encoding** text categories ko numbers me convert karta hai, jaise `Low = 0`, `Medium = 1`, `High = 2`.  
Ye tab use hota hai jab categories me order/ranking ho, example: product size `Small < Medium < Large`.  

**One-Hot Encoding** har category ka separate column banata hai, jaise `City_Lahore`, `City_Karachi`, `City_Islamabad`.  
Ye tab use hota hai jab categories me koi order na ho, example: city, gender, country.  

ML me encoding is liye use hoti hai ky models text ko directly understand nahi karte, unko numbers chahiye hoty hain.  

Real example: `Education Level` ke liye Label Encoding use kar sakty hain, lekin `City Name` ke liye One-Hot Encoding better hai.

## 4. Final Machine Learning Ready Dataset

Now our dataset has:

- Cleaned missing values
- Normalized numerical columns
- Standardized numerical columns
- Encoded categorical columns

This dataset is now more suitable for machine learning.

In [18]:
print("Final Dataset Columns:")
print(df_encoded.columns)

print("Final Dataset Shape:", df_encoded.shape)

display(df_encoded.head())

Final Dataset Columns:
Index(['PassengerId', 'Survived', 'Name', 'Sex', 'Age', 'SibSp', 'Parch',
       'Ticket', 'Fare', 'age_standardized', 'fare_standardized',
       'sex_encoded', 'Embarked_C', 'Embarked_Q', 'Embarked_S', 'Pclass_1',
       'Pclass_2', 'Pclass_3'],
      dtype='object')
Final Dataset Shape: (891, 18)

,PassengerId,Survived,Name,Sex,Age,SibSp,Parch,Ticket,Fare,age_standardized,fare_standardized,sex_encoded,Embarked_C,Embarked_Q,Embarked_S,Pclass_1,Pclass_2,Pclass_3
0,1,0,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,-0.592481,-0.502445,1,False,False,True,False,False,True
1,2,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,0.638789,0.786845,0,True,False,False,True,False,False
2,3,1,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,-0.284663,-0.488854,0,False,False,True,False,False,True
3,4,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,0.407926,0.420730,0,False,False,True,True,False,False
4,5,0,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,0.407926,-0.486337,1,False,False,True,False,False,True

## 5. Save Final Dataset

We can save the final processed dataset as CSV.

In [ ]:
df_encoded.to_csv("titanic_scaled_encoded_dataset.csv", index=False)
print("Dataset saved successfully as titanic_scaled_encoded_dataset.csv")

# Final Summary

Today we learned:

## Feature Scaling
Feature scaling is used to bring numerical values onto a similar scale.

## Normalization
Normalization converts values between 0 and 1.

## Standardization
Standardization converts values around mean 0 and standard deviation 1.

## Encoding
Encoding converts categorical text data into numbers.

## Label Encoding
Best for binary or ordered categories.

## One-Hot Encoding
Best for categories with no order.