

**Assignment:** You are provided with the dataset `Student_Performance.csv`.

In this notebook, we will perform basic data preprocessing:

1. Load the dataset  
2. Check dataset information  
3. Handle missing values  
4. Remove duplicate rows  
5. Clean text columns  
6. Encode categorical columns  
7. Scale numeric columns  
8. Save the cleaned dataset as `Student_Performance_Cleaned.csv`  
9. Optional: find top students and average marks by gender

**Dataset link:** Kaggle — Students Performance Dataset  
https://www.kaggle.com/datasets/rabieelkharoua/students-performance-dataset

In [3]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler, LabelEncoder

In [19]:
df = pd.read_csv('./Student_performance_data _1.csv')

In [21]:
df_2 = pd.read_csv('./Student_performance_data _.csv')

In [22]:
df_2.head()

,StudentID,Age,Gender,Ethnicity,ParentalEducation,StudyTime Weekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA,GradeClass
0,1001,17,1,0,2,19.833723,7,1,2,0,0,1,0,2.929196,2
1,1002,18,0,0,1,15.408756,0,0,1,0,0,0,0,3.042915,1
2,1003,15,0,2,3,4.210570,26,0,2,0,0,0,0,0.112602,4
3,1004,17,1,0,3,10.028829,14,0,3,1,0,0,0,2.054218,3
4,1005,17,1,0,2,4.672495,17,1,3,0,0,0,0,1.288061,4

In [20]:
df.head()

,StudentID,Age,Gender,Ethnicity,Parental Education,StudyTime Weekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA,GradeClass
0,1001,17,1,0,2,19.833723,7,1,2,0,0,1,0,2.929196,2
1,1002,18,0,0,1,15.408756,0,0,1,0,0,0,0,3.042915,1
2,1003,15,0,2,3,4.210570,26,0,2,0,0,0,0,0.112602,4
3,1004,17,1,0,3,10.028829,14,0,3,1,0,0,0,2.054218,3
4,1005,17,1,0,2,4.672495,17,1,3,0,0,0,0,1.288061,4

In [8]:
print("First 5 rows:")
display(df.head())

print("Last 5 rows:")
display(df.tail())

First 5 rows:

,StudentID,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA,GradeClass
0,1001,17,1,0,2,19.833723,7,1,2,0,0,1,0,2.929196,2.0
1,1002,18,0,0,1,15.408756,0,0,1,0,0,0,0,3.042915,1.0
2,1003,15,0,2,3,4.210570,26,0,2,0,0,0,0,0.112602,4.0
3,1004,17,1,0,3,10.028829,14,0,3,1,0,0,0,2.054218,3.0
4,1005,17,1,0,2,4.672495,17,1,3,0,0,0,0,1.288061,4.0

Last 5 rows:

,StudentID,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA,GradeClass
2387,3388,18,1,0,3,10.680555,2,0,4,1,0,0,0,3.455509,0.0
2388,3389,17,0,0,1,7.583217,4,1,4,0,1,0,0,3.279150,4.0
2389,3390,16,1,0,2,6.805500,20,0,2,0,0,0,1,1.142333,2.0
2390,3391,16,1,1,0,12.416653,17,0,2,0,1,1,0,1.803297,1.0
2391,3392,16,1,0,2,17.819907,13,0,2,0,0,0,1,2.140014,1.0

In [9]:
print("Rows and Columns:", df.shape)
print("Total Rows:", df.shape[0])
print("Total Columns:", df.shape[1])

Rows and Columns: (2392, 15)
Total Rows: 2392
Total Columns: 15

## Step 5: Check Column Names

This shows all column names available in the dataset.

In [10]:
print("Column Names:")
print(df.columns.tolist())

Column Names:
['StudentID', 'Age', 'Gender', 'Ethnicity', 'ParentalEducation', 'StudyTimeWeekly', 'Absences', 'Tutoring', 'ParentalSupport', 'Extracurricular', 'Sports', 'Music', 'Volunteering', 'GPA', 'GradeClass']

## Step 6: Basic Dataset Information

`info()` tells us:

- Column names
- Non-null values
- Data types

This is very useful before cleaning the data.

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2392 entries, 0 to 2391
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   StudentID          2392 non-null   int64
 1   Age                2392 non-null   int64
 2   Gender             2392 non-null   int64
 3   Ethnicity          2392 non-null   int64
 4   ParentalEducation  2392 non-null   int64
 5   StudyTimeWeekly    2392 non-null   float64
 6   Absences           2392 non-null   int64
 7   Tutoring           2392 non-null   int64
 8   ParentalSupport    2392 non-null   int64
 9   Extracurricular    2392 non-null   int64
 10  Sports             2392 non-null   int64
 11  Music              2392 non-null   int64
 12  Volunteering       2392 non-null   int64
 13  GPA                2392 non-null   float64
 14  GradeClass         2392 non-null   float64
dtypes: float64(3), int64(12)
memory usage: 280.4 KB

## Step 7: Check Missing Values

Missing values mean empty/null values in the dataset.

We use `isnull().sum()` to check how many missing values are present in each column.

In [12]:
print("Missing values in each column:")
print(df.isnull().sum())

Missing values in each column:
StudentID            0
Age                  0
Gender               0
Ethnicity            0
ParentalEducation    0
StudyTimeWeekly      0
Absences             0
Tutoring             0
ParentalSupport      0
Extracurricular      0
Sports               0
Music                0
Volunteering         0
GPA                  0
GradeClass           0
dtype: int64

## Step 8: Handle Missing Values

Simple beginner rule:

- Numeric columns: fill missing values with mean
- Text/categorical columns: fill missing values with mode

Mean = average value  
Mode = most repeated value

In [ ]:
# Separate numeric and categorical columns
numeric_cols = df.select_dtypes(include=['int64', 'float64']).columns
categorical_cols = df.select_dtypes(include=['object']).columns

print("Numeric Columns:", list(numeric_cols))
print("Categorical Columns:", list(categorical_cols))

# Fill missing numeric values with mean
for col in numeric_cols:
    df[col] = df[col].fillna(df[col].mean())
    
# Fill missing categorical values with mode
for col in categorical_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

print("Missing values after handling:")
print(df.isnull().sum())

Numeric Columns: ['StudentID', 'Age', 'Gender', 'Ethnicity', 'ParentalEducation', 'StudyTimeWeekly', 'Absences', 'Tutoring', 'ParentalSupport', 'Extracurricular', 'Sports', 'Music', 'Volunteering', 'GPA', 'GradeClass']
Categorical Columns: []
Missing values after handling:
StudentID            0
Age                  0
Gender               0
Ethnicity            0
ParentalEducation    0
StudyTimeWeekly      0
Absences             0
Tutoring             0
ParentalSupport      0
Extracurricular      0
Sports               0
Music                0
Volunteering         0
GPA                  0
GradeClass           0
dtype: int64

## Step 9: Remove Duplicate Rows

Duplicate rows are repeated records.

We first check how many duplicates exist, then remove them.

In [14]:
print("Duplicate rows before removing:", df.duplicated().sum())

# df = df.drop_duplicates()

# print("Duplicate rows after removing:", df.duplicated().sum())
# print("New shape:", df.shape)

Duplicate rows before removing: 0

## Step 10: Clean Column Names

Sometimes column names have spaces or capital letters.

We clean them by:

- Converting to lowercase
- Replacing spaces with underscores

Example: `Hours Studied` becomes `hours_studied`

In [23]:
df.head()

,StudentID,Age,Gender,Ethnicity,Parental Education,StudyTime Weekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA,GradeClass
0,1001,17,1,0,2,19.833723,7,1,2,0,0,1,0,2.929196,2
1,1002,18,0,0,1,15.408756,0,0,1,0,0,0,0,3.042915,1
2,1003,15,0,2,3,4.210570,26,0,2,0,0,0,0,0.112602,4
3,1004,17,1,0,3,10.028829,14,0,3,1,0,0,0,2.054218,3
4,1005,17,1,0,2,4.672495,17,1,3,0,0,0,0,1.288061,4

In [24]:
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")

print("Cleaned Column Names:")
print(df.columns.tolist())

Cleaned Column Names:
['studentid', 'age', 'gender', 'ethnicity', 'parental_education', 'studytime_weekly', 'absences', 'tutoring', 'parentalsupport', 'extracurricular', 'sports', 'music', 'volunteering', 'gpa', 'gradeclass']

## Step 11: Clean Text Columns

Text values can contain extra spaces or inconsistent capital letters.

Example:

- ` male ` becomes `Male`
- `female` becomes `Female`

This step only works on text columns.

In [27]:
text_cols = df.select_dtypes(include=['object']).columns
print("Text Columns:", text_cols)


for col in text_cols:
    df[col] = df[col].astype(str).str.strip().str.title()

print("Text columns cleaned:", list(text_cols))
display(df.head())

Text Columns: Index([], dtype='object')
Text columns cleaned: []

,studentid,age,gender,ethnicity,parental_education,studytime_weekly,absences,tutoring,parentalsupport,extracurricular,sports,music,volunteering,gpa,gradeclass
0,1001,17,1,0,2,19.833723,7,1,2,0,0,1,0,2.929196,2
1,1002,18,0,0,1,15.408756,0,0,1,0,0,0,0,3.042915,1
2,1003,15,0,2,3,4.210570,26,0,2,0,0,0,0,0.112602,4
3,1004,17,1,0,3,10.028829,14,0,3,1,0,0,0,2.054218,3
4,1005,17,1,0,2,4.672495,17,1,3,0,0,0,0,1.288061,4

## Step 12: Check Unique Values in Text Columns

This helps us see different categories in each text column.

Example: Male/Female, Yes/No, Grade A/B/C, etc.

In [28]:
for col in text_cols:
    print("Column:", col)
    print(df[col].unique())
    print("-" * 40)

## Step 13: Encode Categorical Columns

Machine learning models do not understand text directly.

So we convert text into numbers.

Here we use **Label Encoding** for beginner level.

Example:

- Yes = 1
- No = 0

In [29]:
label_encoders = {}

for col in text_cols:
    le = LabelEncoder()
    df[col + "_encoded"] = le.fit_transform(df[col])
    label_encoders[col] = le

print("Categorical columns encoded successfully.")
display(df.head())

Categorical columns encoded successfully.

,studentid,age,gender,ethnicity,parental_education,studytime_weekly,absences,tutoring,parentalsupport,extracurricular,sports,music,volunteering,gpa,gradeclass
0,1001,17,1,0,2,19.833723,7,1,2,0,0,1,0,2.929196,2
1,1002,18,0,0,1,15.408756,0,0,1,0,0,0,0,3.042915,1
2,1003,15,0,2,3,4.210570,26,0,2,0,0,0,0,0.112602,4
3,1004,17,1,0,3,10.028829,14,0,3,1,0,0,0,2.054218,3
4,1005,17,1,0,2,4.672495,17,1,3,0,0,0,0,1.288061,4

## Step 14: One-Hot Encoding Alternative

One-Hot Encoding creates separate columns for each category.

Example:

`gender` becomes:

- gender_Male
- gender_Female

We create a separate dataframe `df_onehot` so original encoded dataframe remains safe.

In [ ]:
df_onehot = pd.get_dummies(df, columns=list(text_cols), drop_first=False)

print("One-hot encoded dataset shape:", df_onehot.shape)
display(df_onehot.head())

## Step 15: Scale Numeric Features

Scaling means converting numeric values to a similar range.

Here we use **Min-Max Scaling**, which converts values between 0 and 1.

Formula:

`scaled_value = (value - min) / (max - min)`

In [30]:
# Select numeric columns again after encoding
numeric_cols_after = df.select_dtypes(include=['int64', 'float64']).columns

scaler = MinMaxScaler()

df_scaled = df.copy()
df_scaled[numeric_cols_after] = scaler.fit_transform(df_scaled[numeric_cols_after])

print("Numeric columns scaled between 0 and 1.")
display(df_scaled.head())

Numeric columns scaled between 0 and 1.

,studentid,age,gender,ethnicity,parental_education,studytime_weekly,absences,tutoring,parentalsupport,extracurricular,sports,music,volunteering,gpa,gradeclass
0,0.000000,0.666667,1.0,0.000000,0.50,0.992773,0.241379,1.0,0.50,0.0,0.0,1.0,0.0,0.732299,0.50
1,0.000418,1.000000,0.0,0.000000,0.25,0.771270,0.000000,0.0,0.25,0.0,0.0,0.0,0.0,0.760729,0.25
2,0.000836,0.000000,0.0,0.666667,0.75,0.210718,0.896552,0.0,0.50,0.0,0.0,0.0,0.0,0.028151,1.00
3,0.001255,0.666667,1.0,0.000000,0.75,0.501965,0.482759,0.0,0.75,1.0,0.0,0.0,0.0,0.513555,0.75
4,0.001673,0.666667,1.0,0.000000,0.50,0.233840,0.586207,1.0,0.75,0.0,0.0,0.0,0.0,0.322015,1.00

## Step 16: Final Cleaned Dataset

Now our dataset is cleaned, encoded, and scaled.

We will save it as a CSV file.

In [ ]:
df_scaled.to_csv("Student_Performance_Cleaned.csv", index=False)

print("Cleaned dataset saved successfully as Student_Performance_Cleaned.csv")

## Optional Task 1: Find Top Students by Marks/Performance

Different datasets may have different column names.

This code tries to find a column related to performance or marks, then displays top 5 records.

In [31]:
possible_score_cols = [
    "performance_index", "marks", "score", "exam_score", "final_score", "math_score", "writing_score", "reading_score"
]

score_col = None
for col in possible_score_cols:
    if col in df.columns:
        score_col = col
        break

if score_col:
    print("Score column found:", score_col)
    top_students = df.sort_values(by=score_col, ascending=False).head(5)
    display(top_students)
else:
    print("No marks/performance column found. Please check your column names:")
    print(df.columns.tolist())

No marks/performance column found. Please check your column names:
['studentid', 'age', 'gender', 'ethnicity', 'parental_education', 'studytime_weekly', 'absences', 'tutoring', 'parentalsupport', 'extracurricular', 'sports', 'music', 'volunteering', 'gpa', 'gradeclass']

## Optional Task 2: Average Marks by Gender

This code checks if a gender column exists.

If gender and score columns are available, it calculates average score by gender.

In [ ]:
possible_gender_cols = ["gender", "sex"]

gender_col = None
for col in possible_gender_cols:
    if col in df.columns:
        gender_col = col
        break

if gender_col and score_col:
    print("Average", score_col, "by", gender_col)
    display(df.groupby(gender_col)[score_col].mean())
else:
    print("Gender column or score column not found.")
    print("Available columns:", df.columns.tolist())

## Final Summary

In this notebook, we completed these preprocessing steps:

1. Loaded dataset  
2. Checked rows, columns, and missing values  
3. Filled missing numeric values with mean  
4. Filled missing categorical values with mode  
5. Removed duplicate rows  
6. Cleaned column names  
7. Cleaned text values  
8. Encoded categorical values  
9. Scaled numeric features  
10. Saved final cleaned dataset  

This is the basic preprocessing workflow before machine learning.